default_language_version:
  python: python3
ci:
  autofix_commit_msg: "\U0001F3A8 [pre-commit.ci] Auto format from pre-commit.com hooks"
  autoupdate_commit_msg: '⬆ [pre-commit.ci] pre-commit autoupdate'
  autofix_prs: true
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
          - --keep-runtime-typing
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=98
          - --exclude
          - __init__.py
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args:
          - --line-length=98
        additional_dependencies:
          - black==22.3.0
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
        exclude: CHANGELOG.md
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.211'
    hooks:
    - id: ruff
      args:
      - --fix
      - --target-version=py39
      - --line-length=98
      - --ignore=ANN101,E501,ANN205,ANN003,ANN001,ANN201,ANN202,SIM117,PD013,C901,B007,E722,B006,C417,F821,F841,E741,ANN204,SIM102,PD002,S101
      - --select=ANN,B,BLE,C4,DTZ,E,W,C,F,I,PD,PLW,RUF,S,SIM,TID
