#config for resnet

#shouln't change
channels: 12
out_neurons: 77

#can change
d_model: [12]
n_layers: [4,5,6,7,8] #, 12, 24, 32, 42, 64]
d_conv: [4,5,7] #4 is original
bias: [False]
conv_bias: [True]
pscan: [True]
dt_init: ['random']
expand_factor: [2]
d_state: [6,8,12,16,18] #,8,12,16
