#config for resnet

#shouln't change
channels: 12
out_neurons: 77

#can change
architecture: ['resnet50']
activation: ['leaky_relu','gelu','selu','mish','swish']
dropout: [0.0, 0.5] #two values to allow continuous
use_batchnorm_padding_before_conv1: [False, True] #according to https://github.com/ZFTurbo/classification_models_1D/blob/main/classification_models_1D/models/resnet.py
use_padding_pooling_after_conv1: [False, True] #according to https://github.com/ZFTurbo/classification_models_1D/blob/main/classification_models_1D/models/resnet.py
stochastic_depth: [0.0, 0.5] #two values to allow continuous #https://arxiv.org/pdf/1603.09382.pdf
kernel_sizes:  ['[7, 7, 7, 5, 5]'] # Custom kernel sizes for each stage #according to https://github.com/ZFTurbo/classification_models_1D/blob/main/classification_models_1D/models/resnet.py
strides: ['[2, 2, 2, 2, 2]']
model_width: [1,2]
use_bias: [False]
norm_type: ['batch', 'group','instance']
